blog/urls.py
from django.urls import path
from .views import *
app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/comment/', BlogCommentView.as_view(), name='blog_comment')
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import customer

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blog/', include('blog.urls', namespace='blogs')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('product/', include('product.urls', namespace='product'))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from .views import *

app_name = 'customer'

urlpatterns = [
 path('booking/', BookingPageView.as_view(), name='booking')

]

pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('location/', LocationPageView.as_view(), name='location'),
    path('team/', TeamPageView.as_view(), name='team'),
    path('faqs/', FAQsPageView.as_view(), name='faqs'),
    path('terms/', TermsPageView.as_view(), name='terms'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('gallery/',GalleryView.as_view(), name='gallery')

]

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('menu/', ProductMenuView.as_view(), name='menu'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='single_product'),
    path('<int:pk>/cart/', update_cart, name='add_cart'),
    path('shopping/cart/', CartListView.as_view(), name='shopping_cart')
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class IpModel(models.Model):
    ip = models.CharField(max_length=100)

    def __str__(self):
        return self.ip

class AuthorModel(models.Model):
    first_name = models.CharField(max_length=100, verbose_name=_('first name'))
    last_name = models.CharField(max_length=100, verbose_name=_('last name'))
    avatar = models.ImageField(upload_to='author-avatars/', blank=True, verbose_name=_('avatar'))

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'author'
        verbose_name_plural = 'authors'


class BlogTagModel(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('title'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BlogPostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    description = models.TextField(verbose_name=_('description'))
    main_image = models.ImageField(upload_to='blog-post-img/', verbose_name=_('main image'))
    banner = models.ImageField(upload_to='blog-post-img/', verbose_name=_('banner'))
    author = models.ForeignKey(AuthorModel, on_delete=models.RESTRICT, related_name='posts', verbose_name=_('author'))
    tags = models.ManyToManyField(BlogTagModel, related_name='posts', verbose_name=_('tags'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))
    views = models.ManyToManyField(IpModel, related_name="post_views", blank=True)


    def total_views(self):
        return self.views.count()

    def __str__(self):
        return '{} ...'.format(self.title[:100])

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'


class CommentModel(models.Model):
    post = models.ForeignKey(BlogPostModel,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name=_('post'),
                             )
    name = models.CharField(max_length=64, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    comment = models.TextField(verbose_name=_('comment'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))


    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.name

blog/views.py
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import render, reverse, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView
from taggit.models import Tag
from .form import CommentModelForm
from .models import BlogPostModel, CommentModel
from .form import CommentModelForm


class BlogListView(ListView):
    template_name = 'main/blog.html'
    queryset = BlogPostModel.objects.order_by('-pk')
    model = BlogPostModel
    context_object_name = 'posts'
    paginate_by = 3


class TagIndexView(ListView):
    model = BlogPostModel
    template_name = 'main/blog.html'


    def get_queryset(self):
        return BlogPostModel.objects.filter(tags__slug=self.kwargs.get('tag_slug'))


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class BlogDetailView(DetailView):
    model = BlogPostModel
    template_name = 'main/blog_detail.html'
    context_object_name = 'post'


class BlogCommentView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        form.instance.post = get_object_or_404(BlogPostModel, pk=self.kwargs.get('pk'))
        return super(BlogCommentView, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', kwargs={'pk': self.kwargs.get('pk')})

templates/main/blog_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% load static %}

{% block content %}
    <div id="blog-page" class="page-hero-section division">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="hero-txt text-center white-color">

                        <!-- Breadcrumb -->
                        <div id="breadcrumb">
                            <div class="row">
                                <div class="col">
                                    <div class="breadcrumb-nav">
                                        <nav aria-label="breadcrumb">
                                            <ol class="breadcrumb">
                                                <li class="breadcrumb-item"><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                                                </li>
                                                <li class="breadcrumb-item"><a
                                                        href="{% url 'blog:blog_list' %}">{% trans 'Blog' %}</a></li>
                                                <li class="breadcrumb-item active" aria-current="page">{% trans 'Blog Post' %}</li>
                                            </ol>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Title -->
                        <h2 class="h2-xl">{% trans 'Single Blog Post' %}</h2>

                    </div>
                </div>
            </div>      <!-- End row -->
        </div>       <!-- End container -->
    </div>    <!-- END PAGE HERO -->
    <!-- SINGLE POST
============================================= -->
    <section id="single-post" class="wide-100 single-post-section division">
        <div class="container">


            <!-- SINGLE POST CONTENT -->
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="single-post-wrapper">


                        <!-- SINGLE POST TITLE -->
                        <div class="single-post-title">

                            <!-- TITLE -->
                            <h2 class="h2-xs">{{ post.title }}</h2>


                        </div>    <!-- END SINGLE POST TITLE -->


                        <!-- BLOG POST TEXT -->
                        <div class="single-post-txt">

                            <!-- Text -->
                            <p>{{ post.description }}</p>

                        </div>


                        <!-- BLOG POST INNER IMAGE -->
                        <div class="post-inner-img">
                            <img class="img-fluid" src="{{ post.main_image.url }}" alt="blog-post-image"/>
                        </div>


                        <!-- BLOG POST TEXT -->
                        <div class="single-post-txt">

                            <!-- Text -->
                            <p>{{ post.description }}
                            </p>

                        </div>    <!-- END BLOG POST TEXT -->


                        <!-- SINGLE POST SHARE LINKS -->
                        <div class="row post-share-links d-flex align-items-center">

                            <!-- POST TAGS -->
                            <div class="col-md-9 col-xl-8 post-tags-list">
                                {% for tag in post.tags.all %}
                                    <span><a href="{% url 'blog:blog_list' %}?tag={{ tag }}">{{ tag }}</a></span>
                                {% endfor %}
                            </div>

                            <!-- POST SHARE ICONS -->
                            <div class="col-md-3 col-xl-4 post-share-list text-right">
                                <ul class="share-social-icons text-center clearfix">
                                    <li><a href="#" class="share-ico ico-facebook"><i
                                            class="fab fa-facebook-square"></i></a></li>
                                    <li><a href="#" class="share-ico ico-twitter"><i class="fab fa-twitter"></i></a>
                                    </li>
                                    <li><a href="#" class="share-ico ico-like"><i class="far fa-bookmark"></i></a></li>
                                </ul>
                            </div>

                        </div>    <!-- END SINGLE POST SHARE -->

                    </div>
                </div>
            </div>    <!-- END SINGLE POST CONTENT -->


        </div>     <!-- End container -->
    </section>    <!-- END SINGLE POST -->




    <!-- OTHER POSTS
    ============================================= -->
    <section id="other-posts" class="bg-lightgrey other-posts division">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div id="op-row" class="row d-flex align-items-center">

                        <!-- Previous Post -->
                        <div class="col-md-5">
                            {% if post.get_previous_by_created_at %}
                                <div class="prev-post mb-30">
                                    <h6 class="h6-xl">{% trans 'Previous Post' %}</h6>
                                    <a href="{% url 'blogs:blog_detail' pk=post.get_previous_by_created_at.id %}">{{ post.get_previous_by_created_at.title }}</a>
                                </div>
                            {% endif %}
                        </div>

                        <!-- All Posts -->
                        <div class="col-md-2 text-center">
                            <div class="all-posts mb-30">
                                <a href="{% url 'blog:blog_list' %}"><i class="fas fa-th-large"></i></a>
                            </div>
                        </div>

                        <!-- Next Post -->
                        <div class="col-md-5 text-right">
                            {% if post.get_next_by_created_at %}
                                <div class="next-post mb-30">
                                    <h6 class="h6-xl">{% trans 'Next Post' %}</h6>
                                    <a href="{% url 'blogs:blog_detail' pk=post.get_next_by_created_at.id %}">{{ post.get_next_by_created_at.title }}</a>
                                </div>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>      <!-- End row -->
        </div>
    </section>    <!-- END OTHER POSTS -->




    <!-- POST COMMENTS
    ============================================= -->
    <section id="post-comments" class="wide-80 post-comments division">
        <div class="container">
            <div class="row">


                <!-- COMMENTS WRAPPER -->
                <div class="col-lg-10 offset-lg-1">
                    <div class="comments-wrapper">

                        <!-- Title -->
                        {% if post.comments.all %}
                            <h5 class="h5-lg">{{ post.comments.all.count }} {% trans 'Comments' %}</h5>
                        {% endif %}


                        <!-- COMMENT #1 -->
                        {% for comment in post.comments.all %}
                            <div class="media">

                                <!-- Comment-4 Avatar -->
                                <img class="mr-3" src="{% static 'images/post-author-4.jpg'%}" alt="comment-avatar">

                                <div class="media-body">

                                    <!-- Comment-4 Meta -->
                                    <div class="comment-meta">
                                        <h6 class="h6-md mt-0">{{ comment.name }}</h6>
                                        <span class="comment-date">{{ comment.created_at|timesince }} ago&#8194;- </span>
                                        <span class="btn-reply"><a href="#leave-comment" class="internal-link"><i
                                                class="fas fa-reply"></i> Reply</a></span>
                                    </div>

                                    <!-- Comment-4 Text -->
                                    <p>{{ comment.comment }}</p>
                                    </p>

                                </div>
                            </div>    <!-- END COMMENT #4 -->


                            <hr/>
                        {% endfor %}
                        <!-- COMMENT FORM -->
                        <div id="">

                            <!-- Title -->
                            <h5 class="h5-lg">{% trans 'Leave a Comment' %}</h5>

                            <!-- Text -->
                            <p class="p-sm grey-color">Your email address will not be published. Required fields are
                                marked *</p>

                            <form action="{% url 'blog:blog_comment' pk=post.id %}" method="POST"
                                  class="row comment-form">
                                {% csrf_token %}
                                <div class="col-md-12 input-message">
                                    <p>{% trans 'Add Comment' %} *</p>
                                    <textarea class="form-control " name="comment" rows="6"
                                              placeholder="Enter Your Comment Here* ..." required></textarea>
                                </div>

                                <div class="col-md-12">
                                    <p>{% trans 'Name' %}*</p>
                                    <input type="text" name="name" class="form-control"
                                           placeholder="Enter Your Name*" required>
                                </div>

                                <div class="col-md-12">
                                    <p>Email*</p>
                                    <input type="email" name="email" class="form-control email"
                                           placeholder="Enter Your Email*" required>
                                </div>

                                <!-- Contact Form Button -->
                                <div class="col-lg-12 form-btn">
                                    <button type="submit" class="btn btn-red tra-red-hover submit">Post Comment</button>
                                </div>
                                {##}
                                {#                                <!-- Contact Form Message -->#}
                                {#                                <div class="col-md-12 comment-form-msg text-center">#}
                                {#                                    <div class="sending-msg"><span class="loading"></span></div>#}
                                {#                                </div>#}

                            </form>

                        </div>    <!-- END COMMENT FORM -->

                    </div>
                </div>    <!-- END COMMENTS WRAPPER -->


            </div>     <!-- End row -->
        </div>     <!-- End container -->
    </section>    <!-- END POST COMMENTS -->




    <!-- NEWSLETTER-1
    ============================================= -->
    <section id="newsletter-1" class="mb-20 newsletter-section division">
        <div class="container">
            <div class="inner-bg bg-lightgrey">
                <div class="row">


                    <!-- NEWSLETTER FORM -->
                    <div class="col-md-10 col-xl-8 offset-md-1 offset-xl-2">
                        <div class="newsletter-txt text-center">

                            <!-- Title -->
                            <h3 class="h3-sm">Subscribe To Newsletter</h3>

                            <!-- Text -->
                            <p class="p-md grey-color">Subscribe to the weekly newsletter for all the latest updates</p>

                            <!-- Form -->
                            <form class="newsletter-form">

                                <div class="input-group">
                                    <input type="email" class="form-control" placeholder="Your email address" required
                                           id="s-email">
                                    <span class="input-group-btn">
												<button type="submit" class="btn btn-red tra-red-hover">Sign Up</button>
											</span>
                                </div>

                                <!-- Newsletter Form Notification -->
                                <label for="s-email" class="form-notification"></label>

                            </form>

                        </div>
                    </div>      <!-- END NEWSLETTER FORM -->


                </div>     <!-- End row -->
            </div>    <!-- End Inner Bg -->
        </div>       <!-- End container -->
    </section>    <!-- END NEWSLETTER-1 -->
{% endblock %}

templates/main/menu1.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load my_tags %}
{% block content %}
    <!-- PAGE CONTENT
============================================= -->
    <div id="page" class="page">


        <!-- PAGE HERO
        ============================================= -->
        <div id="menu-page" class="page-hero-section division">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 offset-lg-1">
                        <div class="hero-txt text-center white-color">

                            <!-- Breadcrumb -->
                            <div id="breadcrumb">
                                <div class="row">
                                    <div class="col">
                                        <div class="breadcrumb-nav">
                                            <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item"><a
                                                            href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                                                    <li class="breadcrumb-item active" aria-current="page">Menu</li>
                                                </ol>
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Title -->
                            <h2 class="h2-xl">{% trans 'Main Menu' %} </h2>

                        </div>
                    </div>
                </div>      <!-- End row -->
            </div>       <!-- End container -->
        </div>    <!-- END PAGE HERO -->


        <!-- MENU-6
        ============================================= -->
        <section id="menu-6" class="wide-70 menu-section division">
            <div class="container">
                <div class="row">

                    {% for food in menu_items %}
                        <!-- MENU ITEM #1 -->
                        <div class="col-sm-6 col-lg-3">
                            <div class="menu-6-item bg-white">

                                <!-- IMAGE -->
                                <div class="menu-6-img rel">
                                    <div class="hover-overlay">

                                        <!-- Image -->
                                        <img class="img-fluid" src="{{ food.image.url }}" alt="menu-image"/>

                                        <!-- Item Code -->
                                        <span class="item-code bg-tra-dark">Code: {{ food.id }}</span>

                                        <!-- Zoom Icon -->
                                        <div class="menu-img-zoom ico-25">
                                            <a href="{{ food.image.url }}" class="image-link">
                                                <span class="flaticon-zoom"></span>
                                            </a>
                                        </div>

                                    </div>
                                </div>

                                <!-- TEXT -->
                                <div class="menu-6-txt rel">

                                    <!-- Rating -->
                                    <div class="item-rating">
                                        <div class="stars-rating stars-lg">
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star-half-alt"></i>
                                        </div>
                                    </div>

                                    <!-- Like Icon -->
                                    <div class="like-ico ico-25">
                                        <a href="#"><span class="flaticon-heart"></span></a>
                                    </div>

                                    <!-- Title -->
                                    <a href="{% url 'product:single_product' food.id %}"><h5
                                            class="h5-sm">{{ food.name }}</h5>
                                    </a>

                                    <!-- Description -->
                                    {% for ingredient in food.ingredient.all %}
                                        <span class="grey-color">{{ ingredient }},</span>
                                    {% endfor %}
                                    <br><br>
                                    <!-- Price -->
                                    <div class="menu-6-price bg-coffee">
                                        <h5 class="h5-xs yellow-color">$
                                            {% if food.is_discount %}
                                                {{ food.real_price }}
                                            {% else %}
                                                {{ food.price }}
                                            {% endif %}</h5>
                                    </div>

                                    <!-- Add To Cart -->
                                    <div class="add-to-cart bg-yellow ico-10">
                                        {% if request|is_cart:food %}
                                            <a href="{% url 'product:add_cart' pk=food.pk %}?next={{ request.path }}"
                                               class="add-cart">- Remove From Cart</a>
                                        {% else %}
                                            <a href="{% url 'product:add_cart' pk=food.pk %}?next={{ request.path }}"
                                               class="add-cart">+ Add To Cart</a>
                                        {% endif %}
                                    </div>

                                </div>

                            </div>
                        </div>    <!-- END MENU ITEM #1 -->
                    {% endfor %}
                </div>      <!-- End row -->
            </div>       <!-- End container -->
        </section>    <!-- END MENU-6 -->

        {% if page_obj.paginator.count > 8 %}
            <!-- PAGE PAGINATION
            ============================================= -->
            <div class="bg-color-01 page-pagination division">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation">
                                <ul class="pagination justify-content-center">

                                    <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1"><i
                                            class="fas fa-angle-left"></i></a></li>
                                    {% for page in page_obj.paginator.page_range %}
                                        <li {% if page == page_obj.number %}class="page-item active"{% endif %}><a
                                                class="page-link" href="?page={{ page }}">{{ page }}</a>
                                        </li>
                                    {% endfor %}
                                    <li class="page-item"><a class="page-link" href="#"><i
                                            class="fas fa-angle-right"></i></a></li>

                                </ul>
                            </nav>

                        </div>
                    </div>  <!-- End row -->
                </div> <!-- End container -->
            </div>    <!-- END PAGE PAGINATION -->
        {% endif %}

        <!-- BANNER-4
        ============================================= -->
        <section id="banner-4" class="bg-fixed wide-100 banner-section division">
            <div class="container">
                <div class="row">


                    <!-- BANNER TEXT -->
                    <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
                        <div class="banner-4-txt text-center">

                            <!-- Title  -->
                            <h4 class="h4-xl">We Guarantee</h4>

                            <!-- Title  -->
                            <h2>30 Minutes Delivery!</h2>

                            <!-- Text -->
                            <p class="p-lg">Aliquam a augue suscipit, luctus neque purus ipsum neque undo dolor primis
                                libero tempus,
                                blandit a cursus varius luctus neque magna
                            </p>

                            <!-- Call Button -->
                            <a href="tel:123456789" class="btn btn-lg btn-red tra-red-hover">Call: 789-654-3210</a>

                        </div>
                    </div>


                </div>      <!-- End row -->
            </div>        <!-- End container -->
        </section>    <!-- END BANNER-4 -->
    </div>    <!-- END PAGE CONTENT -->

{% endblock %}