blog/urls.py
from django.urls import path
from .views import *
app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/comment/', BlogCommentView.as_view(), name='blog_comment')
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import customer

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blog/', include('blog.urls', namespace='blogs')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('product/', include('product.urls', namespace='product'))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from .views import *

app_name = 'customer'

urlpatterns = [
 path('booking/', BookingPageView.as_view(), name='booking')

]

pages/urls.py
from django.urls import path

from .views import *

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('location/', LocationPageView.as_view(), name='location'),
    path('team/', TeamPageView.as_view(), name='team'),
    path('faqs/', FAQsPageView.as_view(), name='faqs'),
    path('terms/', TermsPageView.as_view(), name='terms'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('gallery/',GalleryView.as_view(), name='gallery')

]

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('menu/', ProductMenuView.as_view(), name='menu'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='single_product'),
    path('<int:pk>/cart/', update_cart, name='add_cart'),
    path('shopping/cart/', CartListView.as_view(), name='shopping_cart')
]

templates/layouts/footer.html
{% load static %}
{% load i18n %}

   <!-- FOOTER-1
    ============================================= -->
    <footer id="footer-1" class="footer division">
        <div class="container">
            <div class="row">


                <!-- FOOTER INFO -->
                <div class="col-md-5 col-lg-4 col-xl-4">
                    <div class="footer-info mb-40">

                        <!-- Footer Logo -->
                        <div class="footer-logo"><img src="{% static 'images/logo-01.png' %} " alt="footer-logo"/></div>

                        <!-- Footer Copyright -->
                        <p>&copy; {% trans '2020 Testo. All Rights Reserved' %}</p>

                    </div>
                </div>


                <!-- FOOTER CONTACTS -->
                <div class="col-md-7 col-lg-4 col-xl-5">
                    <div class="footer-contacts mb-40">

                        <!-- Address -->
                        <p class="p-xl mt-10">Los Angeles,</p>
                        <p class="p-xl">8721 M Central Avenue, CA 90036</p>

                        <!-- Contacts -->
                        <p class="p-lg foo-email">Email: <a href="mailto:yourdomain@mail.com">hello@yourdomain.com</a>
                        </p>
                        <p class="p-lg">{% trans 'Call Now' %}: <span class="yellow-color"><a
                                href="tel:123456789">789-654-3210</a></span></p>

                    </div>
                </div>


                <!-- FOOTER INSTAGRAM -->
                <div class="col-md-12 col-lg-4 col-xl-3">
                    <div class="footer-img mb-40">

                        <!-- Images -->
                        <ul class="text-center clearfix">
                            <li><a href="#" target="_blank"><img class="insta-img" src="{% static 'images/instagram/img-01.jpg' %} "
                                                                 alt="insta-img"></a></li>
                            <li><a href="#" target="_blank"><img class="insta-img" src="{% static 'images/instagram/img-02.jpg' %} "
                                                                 alt="insta-img"></a></li>
                            <li><a href="#" target="_blank"><img class="insta-img" src="{% static 'images/instagram/img-03.jpg' %} "
                                                                 alt="insta-img"></a></li>
                            <li><a href="#" target="_blank"><img class="insta-img" src="{% static 'images/instagram/img-04.jpg' %} "
                                                                 alt="insta-img"></a></li>
                            <li><a href="#" target="_blank"><img class="insta-img" src="{% static 'images/instagram/img-05.jpg' %} "
                                                                 alt="insta-img"></a></li>
                            <li><a href="#" target="_blank"><img class="insta-img" src="{% static 'images/instagram/img-06.jpg' %} "
                                                                 alt="insta-img"></a></li>
                        </ul>

                    </div>
                </div>    <!-- END FOOTER IMAGES -->


            </div>      <!-- End row -->
        </div>       <!-- End container -->
    </footer>    <!-- END FOOTER-1 -->

templates/layouts/navbar.html
{% load static %}
{% load i18n %}
{% load my_tags %}

<!-- PRELOADER SPINNER
============================================= -->
{#<div id="loader-wrapper">#}
{#    <div id="loader">#}
{#        <div class="cssload-spinner">#}
{#            <div class="cssload-ball cssload-ball-1"></div>#}
{#            <div class="cssload-ball cssload-ball-2"></div>#}
{#            <div class="cssload-ball cssload-ball-3"></div>#}
{#            <div class="cssload-ball cssload-ball-4"></div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
<!-- HEADER-1
============================================= -->
<header id="header-1" class="header navik-header header-shadow center-menu-1 header-transparent">
    <div class="container">


        <!-- NAVIGATION MENU -->
        <div class="navik-header-container">


            <!-- CALL BUTTON -->
            <div class="callusbtn"><a href="tel:123456789"><i class="fas fa-phone"></i></a></div>


            <!-- LOGO IMAGE -->
            <div class="logo" data-mobile-logo="{% static 'images/logo-01.png' %}"
                 data-sticky-logo="{% static 'images/logo-01.png' %}">
                <a href="{% url 'pages:home' %}"><img src="{% static 'images/logo-01.png' %}" alt="header-logo"/></a>
            </div>


            <!-- BURGER MENU -->
            <div class="burger-menu">
                <div class="line-menu line-half first-line"></div>
                <div class="line-menu"></div>
                <div class="line-menu line-half last-line"></div>
            </div>


            <!-- MAIN MENU -->
            <nav class="navik-menu menu-caret navik-yellow">
                <ul class="top-list">

                    <!-- DROPDOWN MENU -->
                    <li><a href="#">{% trans 'About' %}</a>
                        <ul>
                            <li><a href="{% url 'pages:about' %}">{% trans 'About Testo' %}</a></li>
                            <li><a href="{% url 'pages:team' %}">{% trans 'Meet The Team' %}</a></li>
                            <li><a href="{% url 'pages:gallery' %}">{% trans 'Images Gallery' %}</a></li>
                            <li><a href="{% url 'pages:faqs' %}">{% trans 'F.A.Q.s' %}</a></li>
                            <li><a href="{% url 'pages:terms' %}">{% trans 'Terms & Privacy' %}</a></li>
                        </ul>
                    </li>

                    <!-- DROPDOWN MENU -->
                    <li><a href="#">{% trans 'Our Menu' %}</a>
                        <ul>
                            <li><a href="menu-1.html">Menu v.1 - Tabs Cards</a></li>
                            <li><a href="{% url 'product:menu' %}">Menu v.2 - Cards</a></li>
                            <li><a href="menu-3.html">Menu v.3 - Sections</a></li>
                        </ul>
                    </li>
                </ul>
                <ul>
                    <!-- DROPDOWN MENU -->
                    <li><a href="{% url 'blog:blog_list' %}">{% trans 'Blog' %}</a>

                    </li>
                    '
                    <!-- DROPDOWN MENU -->
                    <li><a href="#">{% trans 'Contacts' %}</a>
                        <ul>
                            <li><a href="{% url 'customer:booking' %}">{% trans 'Book A Table' %}</a></li>
                            <li><a href="{% url 'pages:location' %}">{% trans 'Our Locations' %}</a></li>
                            <li><a href="{% url 'pages:contact' %}">{% trans 'Contact Us' %}</a></li>
                        </ul>
                    </li>

                    {% get_current_language as current_lang %}
                    <li><a href="">{{ current_lang }}</a>
                        <ul>
                            {% get_available_languages as languages %}
                            {% for lan in languages %}
                                {% if lan.0 != current_lan %}
                                    <li>
                                        <a href="/{{ lan.0 }}/{{ request.path|slice:'4:' }}"
                                           style="text-decoration: none; color: black;">{{ lan.1|upper }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </li>

                    <!-- BASKET ICON -->
                    <li class="basket-ico ico-30">
                        {% get_cart_info request as cart_info %}
                        <a href="{% url 'product:shopping_cart' %}">
                            <span class="ico-holder"><span class="flaticon-shopping-bag"></span> <em
                                    class="roundpoint">{{ cart_info.0 }}</em></span>
                        </a>
                    </li>


                </ul>
            </nav>    <!-- END MAIN MENU -->


        </div>    <!-- END NAVIGATION MENU -->


    </div>     <!-- End container -->
</header>    <!-- END HEADER-1 -->